apiVersion: batch/v1
kind: CronJob
metadata:
  name: restaceratops-nightly
  namespace: testing
spec:
  schedule: "0 1 * * *"  # Daily at 1 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restaceratops
            image: ghcr.io/your-org/restaceratops:latest
            env:
            - name: BASE_URL
              value: "https://your-api.com"
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: bearer-token
            - name: PUSHGATEWAY_URL
              value: "http://prometheus-pushgateway:9091"
            volumeMounts:
            - name: test-config
              mountPath: /app/tests
              readOnly: true
          volumes:
          - name: test-config
            configMap:
              name: restaceratops-tests
          restartPolicy: Never
          backoffLimit: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaceratops-tests
  namespace: testing
data:
  "api-tests.yml": |
    - name: "Health Check"
      request:
        method: GET
        url: https://your-api.com/health
      expect:
        status: 200
    - name: "User Authentication"
      request:
        method: POST
        url: https://your-api.com/auth/login
        json:
          username: "testuser"
          password: "testpass"
      expect:
        status: 200
        save:
          token: $.access_token
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: testing
type: Opaque
data:
  bearer-token: <base64-encoded-token> 